# App settings
DASH_DEBUG: false
DASH_HOST: '0.0.0.0'
DASH_PORT: 8050
TEMP_FOLDER: './temp'

# logging
LOG_LEVEL: DEBUG
WEB_LOG_LEVEL: DEBUG
SENTRY_LEVEL: INFO
SENTRY_EVENT_LEVEL: ERROR
SENTRY_DSN: https://d3e89a5a74d4466ab87439f260ade659@o56764.ingest.sentry.io/4504724090781696

# App settings
APP_NAME: Hakai Quality Control
NAVBAR_COLOR: '#B52026'
NAVBAR_DARK: true

# Hakai endpoints
HAKAI_DEFAULT_API_SERVER_ROOT: https://hecate.hakai.org/api
HAKAI_ENDPOINTS: 'ctd/views/file/cast'

PRIMARY_VARIABLES: [sio2, po4, no2_no3_um]

VARIABLES_LABEL:
  {
    'sio2': 'SiO2 (uM)',
    'po4': 'PO4 (uM)',
    'no2_no3_um': 'NO2 NO3 (uM)',
    'line_out_depth': 'Bottle Target Depth (m)',
    'collected': 'Collection Time',
    'AV': 'Accepted Value',
    'UKN': 'Unknown',
    'NA': 'Not Available',
    'SVC': 'Suspicious Value Careful',
    'SVD': 'Suspicious Value Discard',
    'BDL': 'Below Detection Limit',
  }
