version: '3'
services:
  dashboard:
    env_file:
      - .env
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: .
    ports:
      - "8050:8050"
    environment:
      - DASH_HOST=0.0.0.0
      - DASH_DEBUG=False
    container_name: hakai-oceanography-qc
    volumes:
      - ./logs:/code/logs
