name: Deploy main to hakai.app
on:
  push:
    branches:
      - main
jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: altinukshini/deployment-action@releases/v1
        name: Create GitHub deployment
        id: main
        with:
          token: '${{ github.token }}'
          target_url: https://quality-control-data.server.hakai.app/
          environment: production
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Caprover CLI
        run: npm install -g caprover
      - name: Tell Caprover server to deploy main
        run: caprover deploy --caproverUrl https://captain.server.hakai.app --appToken ${{ secrets.CAPROVER_TOKEN_MAIN }} --branch 'main' --appName quality-control-data
