name: Deploy development to hak4i.org
on:
  push:
    branches:
      - development
jobs:
  deploy-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: altinukshini/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          target_url: https://quality-control-data.server.hak4i.org/
          environment: development
      - name: Install Caprover CLI
        run: npm install -g caprover
      - name: Tell Caprover server to deploy development
        run: caprover deploy --caproverUrl https://captain.server.hak4i.org --appToken ${{ secrets.CAPROVER_TOKEN }} --branch 'development' --appName quality-control-data
      - name: Update deployment status (success)
        if: success()
        uses: altinukshini/deployment-status@releases/v1
        with:
          token: '${{ github.token }}'
          target_url: https://quality-control-data.server.hak4i.org/
          state: 'success'
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: altinukshini/deployment-status@releases/v1
        with:
          token: '${{ github.token }}'
          target_url: https://quality-control-data.server.hak4i.org/
          state: 'failure'
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
