name: Deploy development to hak4i.org
on:
  pull_request:
    branches:
      - main
      - development
jobs:
  deploy-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install packages
        run: pip install -e '.[dev]'
      - name: Run Pytests
        run: pytest
